import streamlit as st

def app():
    st.title("Terms of Use")

    st.markdown("""

    **Effective Date:** June 1, 2024

    ## Introduction

    Welcome to Chatbot.ai. By using our website and services, you agree to comply with and be bound by these terms of use. Please review the following terms carefully.

    ## Use of the Site

    1. **Eligibility:** You must be at least 10 years old to use our services. By using our services, you represent and warrant that you meet this age requirement.
    2. **Prohibited Activities:** You agree not to use our services for any unlawful or prohibited activities, including but not limited to:
        - Posting or transmitting any content that is harmful, offensive, or otherwise objectionable.
        - Impersonating any person or entity, or falsely stating or otherwise misrepresenting your affiliation with a person or entity.
        - Engaging in any activity that interferes with or disrupts our services.

    ## Intellectual Property

    All content, features, and functionality on our website, including but not limited to text, graphics, logos, and software, are the exclusive property of Chatbot.ai or its licensors and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.

    ## Disclaimers

    1. **No Warranty:** Our services are provided "as is" and "as available" without any warranties of any kind, either express or implied. We do not warrant that our services will be uninterrupted or error-free.
    2. **Limitation of Liability:** In no event shall Chatbot.ai or its affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from:
        - Your use or inability to use our services.
        - Any unauthorized access to or use of our servers and/or any personal information stored therein.
        - Any bugs, viruses, trojan horses, or the like that may be transmitted to or through our services by any third party.
        - The response is generated by Artificial Intelligence so the accuracy of contents is related with the findings of Artificial Intelligence

    ## Changes to Terms

    We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page. You are advised to review these Terms periodically for any changes.

    ## Governing Law

    These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which Chatbot.ai operates, without regard to its conflict of law provisions.

    ## Contact Us

    If you have any questions about these Terms, please contact us at:
    **Email:** [chatbot.aidm@gmail.com](mailto:chatbot.aidm@gmail.com)

    Thank you for using Chatbot.ai.
    """)
    
if __name__ == "__main__":
    app()
